import allure
from utils.links import *
from pages.order_page import OrderPage
from pages.account_access_page import AccountAccessPage


class TestOrderPage:

    @allure.title('Проверка появления всплывающего окна после клика по заказу')
    def test_visible_popup_order_after_clicking_on_a_ingredient(self, driver_setup):
        order_page = OrderPage(driver_setup)
        order_page.get_to_link(Links.feed_page)
        order_page.wait_link_account_visibility()
        order_page.click_order_in_order_dashboard()
        assert order_page.is_title_config_order_visible() == True

    @allure.title('Проверка идентичности отображения заказов на странице истории и ленты заказов')
    def test_identical_order_id(self, driver_setup, setup_user):
        order_page = OrderPage(driver_setup)
        account_access_page = AccountAccessPage(driver_setup)
        order_page.get_to_link(Links.main_page)
        order_page.wait_link_account_visibility()
        order_page.click_account_link()
        email = setup_user.get('email')
        password = setup_user.get('password')
        account_access_page.set_email(email)
        account_access_page.set_password(password)
        account_access_page.click_authorization_button()
        order_page.wait_checkout_button_visibility()
        order_page.add_ingredients_to_order_cart()
        order_page.click_to_checkout_button()
        order_page.wait_clickable_id_order()
        order_page.wait_until_not_9999()
        order_page.click_to_cross()
        order_page.wait_dashboard_link_visibility()
        order_page.click_account_link()
        order_page.wait_for_overlay_to_disappear()
        account_access_page.click_link_order_history()
        order_page.wait_all_order_list_in_dashboard_visibility()
        feed_locator = order_page.getting_all_order_service()
        history_locator = order_page.getting_all_order_user()
        assert order_page.compare_orders(history_locator, feed_locator) == True

    @allure.title('Проверка увелечения счетчика "за все время" после совершения заказа')
    def test_all_time_counter_value_increases(self, driver_setup, setup_user):
        order_page = OrderPage(driver_setup)
        account_access_page = AccountAccessPage(driver_setup)
        order_page.get_to_link(Links.feed_page)
        order_page.wait_link_account_visibility()
        counter_value = order_page.getting_count_orders()
        order_page.click_account_link()
        account_access_page.wait_authorization_form_title_visibility()
        email = setup_user.get('email')
        password = setup_user.get('password')
        account_access_page.set_email(email)
        account_access_page.set_password(password)
        account_access_page.click_authorization_button()
        order_page.wait_checkout_button_visibility()
        order_page.add_ingredients_to_order_cart()
        order_page.click_to_checkout_button()
        order_page.wait_clickable_id_order()
        order_page.wait_until_not_9999()
        order_page.click_to_cross()
        order_page.wait_dashboard_link_visibility()
        order_page.click_dashboard_link()
        order_page.wait_dashboard_link_visibility()
        current_value = order_page.getting_count_orders()
        assert current_value > counter_value

    @allure.title('Проверка увелечения счетчика "за все сегодня" после совершения заказа')
    def test_daily_time_counter_value_increases(self, driver_setup, setup_user):
        order_page = OrderPage(driver_setup)
        account_access_page = AccountAccessPage(driver_setup)
        order_page.get_to_link(Links.feed_page)
        order_page.wait_link_account_visibility()
        counter_value = order_page.getting_daily_count_orders()
        order_page.click_account_link()
        account_access_page.wait_authorization_form_title_visibility()
        email = setup_user.get('email')
        password = setup_user.get('password')
        account_access_page.set_email(email)
        account_access_page.set_password(password)
        account_access_page.click_authorization_button()
        order_page.wait_checkout_button_visibility()
        order_page.add_ingredients_to_order_cart()
        order_page.click_to_checkout_button()
        order_page.wait_clickable_id_order()
        order_page.wait_until_not_9999()
        order_page.click_to_cross()
        order_page.wait_dashboard_link_visibility()
        order_page.click_dashboard_link()
        order_page.wait_dashboard_link_visibility()
        current_value = order_page.getting_daily_count_orders()
        assert current_value > counter_value

    @allure.title('Проверка отображения идентификатора заказа в разделе "В работе" после совершения заказа')
    def test_visible_id_in_work_order(self, driver_setup, setup_user):
        order_page = OrderPage(driver_setup)
        account_access_page = AccountAccessPage(driver_setup)
        order_page.get_to_link(Links.main_page)
        order_page.wait_link_account_visibility()
        order_page.click_account_link()
        account_access_page.wait_authorization_form_title_visibility()
        email = setup_user.get('email')
        password = setup_user.get('password')
        account_access_page.set_email(email)
        account_access_page.set_password(password)
        account_access_page.click_authorization_button()
        order_page.wait_checkout_button_visibility()
        order_page.add_ingredients_to_order_cart()
        order_page.click_to_checkout_button()
        order_page.wait_clickable_id_order()
        order_page.wait_until_not_9999()
        order_id_in_form = order_page.getting_order_id()
        order_page.click_to_cross()
        order_page.wait_dashboard_link_visibility()
        order_page.click_dashboard_link()
        order_page.wait_dashboard_link_visibility()
        number_of_order = order_page.getting_number_order()
        assert f'0{order_id_in_form}' == number_of_order
